### PR TITLE
Catch up

### PR DESCRIPTION
**Pull request by anon-software**
This webhook is quite outdated. This pull request includes updates that have been introduced into the webhook example in the meantime. Considering that it is also behind cert-manager (I created a pull request for it too), additional changes are bringing this webhook up to the latest cert-manager code. In addition, the tests can now run on arm64 based Raspberry PI OS. Another new feature is automated build within GitHub and publishing the binaries to your DockerHub repository to which you can define the credentials for in your GitHub repository.

### CODE REVIEW

**Review by Dopingus — APPROVED** [review]
Thanks for the PR. Looks good to me.

**Comment by Dopingus** [comment]
I will define some credentials after I have read up on credential management in Github.
Thanks a lot though. I haven't used this in quite a while, so it has become outdated quite a bit as you mentioned.

**Comment by anon-software** [comment]
You are welcome. I was surprised how quickly you got to review it.
I included a link to the write-up about Docker Hub connection into the commit comment. Basically, you just need to enter Docker Hub credentials into your Git Hub repository.
I am personally learning Kubernetes and in the process I am transferring some services I run from multiple home home computers to a Raspberry PI cluster. Since I use dynu to access them from outside, your webhook was exactly what I needed. It took me several days to bring it up to date though because I do not speak "go" and had no clue what I was doing!
Marko
    On Thursday, July 28, 2022 at 12:10:52 p.m. PDT, Thao-Nguyen Do ***@***.***> wrote:  
 
 


I will define some credentials after I have read up on credential management in Github.
Thanks a lot though. I haven't used this in quite a while, so it has become outdated quite a bit as you mentioned.

**Comment by Dopingus** [comment]
I did the same thing a year ago. I started to migrate everything from running in plain containers to running Kubernetes everywhere. However, I started to use Cloudflare's free tier soon afterwards which has replaced most of my Dynu stuff.
Then again, I have to admit that I might be vendor-locked if Cloudflare decides to reduce their free tier.

I'm also not a Go developer so I probably went through the same issues as you did. I'm really thankful for some automation. Back when I setup this webhook I should have setup some Github action for automated tests. I never got around to add this later on.

btw. I added the credentials, it should work now.

Cheers!

**Comment by anon-software** [comment]
Hi, I have been studying webhooks for the past few days, and I think you misunderstood the "group name" concept. The comment in values.yaml file states the following:
# The GroupName here is used to identify your company or business unit that
# created this webhook.
# For example, this may be "acme.mycompany.com".
# This name will need to be referenced in each Issuer's `webhook` stanza to
# inform cert-manager of where to send ChallengePayload resources in order to
# solve the DNS01 challenge.
# This group name should be **unique**, hence using your own company's domain
# here is recommended.

I think the idea was to avoid the name collision if, for example, two people named their webhooks as "dynu". We should set our group names to something that is globally unique which is why they suggest using the domain name there.
I am working on another pull request and I was thinking about changing that value to dopingus.github.io. yourcompany.or.yourorg that you put there does not make sense to me, it is not about the webhook user but author as I understand it.
Marko

    On Thursday, July 28, 2022 at 12:27:03 p.m. PDT, Thao-Nguyen Do ***@***.***> wrote:  
 
 


I did the same thing a year ago. I started to migrate everything from running in plain containers to running Kubernetes everywhere. However, I started to use Cloudflare's free tier soon afterwards which has replaced most of my Dynu stuff.
Then again, I have to admit that I might be vendor-locked if Cloudflare decides to reduce their free tier.

I'm also not a Go developer so I probably went through the same issues as you did. I'm really thankful for some automation. Back when I setup this webhook I should have setup some Github action for automated tests. I never got around to add this later on.

btw. I added the credentials, it should work now.

Cheers!

**Comment by Dopingus** [comment]
Hi Marko,

you're right about that!
I dismissed this value as something that should be set just like many other Helm chart values. PR for it is up: https://github.com/Dopingus/cert-manager-webhook-dynu/pull/5


Regards

**Comment by anon-software** [comment]
All right, I shall create another pull request today or tomorrow. It will be mostly about further usage simplification like the one you already made.
Marko
    On Tuesday, August 2, 2022 at 12:58:55 a.m. PDT, Thao-Nguyen Do ***@***.***> wrote:  
 
 


Hi Marko,

you're right about that!
I dismissed this value as something that should be set just like many other Helm chart values. PR for it is up: #5

Regards

**Pull request merged**
