### PR TITLE
Fix installation instructions in README

### PR DESCRIPTION
**Pull request by Dopingus**
Fixes the documentation instructions to working commands

### CODE REVIEW

**Comment by anon-software** [comment]
We need to update this line too:
```
groupName: <YOUR_GROUP_NAME> # Use the groupName defined above
```
The group name is hardcoded to com.github.dopingus.cert-manager-webhook-dynu, it is not up to the user to choose it.

Further, the version number in chart.yaml should be updated too. Yes, it is pointless to do it for a README file change but the automatic build will fail if left unchanged.

**Comment by Dopingus** [comment]
> We need to update this line too:
> 
> ```
> groupName: <YOUR_GROUP_NAME> # Use the groupName defined above
> ```
> 
> The group name is hardcoded to com.github.dopingus.cert-manager-webhook-dynu, it is not up to the user to choose it.
> 
> Further, the version number in chart.yaml should be updated too. Yes, it is pointless to do it for a README file change but the automatic build will fail if left unchanged.

I think the group name is already hard coded. I incremented the version in the chart.yaml as per your suggestions.
Please kindly review again.

**Comment by anon-software** [comment]
Yes, the group name is set in the code, but README.md does not reflect it. Line 60 (or about) says
```
groupName: <YOUR_GROUP_NAME> # Use the groupName defined above
```
but it should match what is in the code and look like this:
```
groupName: com.github.dopingus.cert-manager-webhook-dynu
```

**Comment by Dopingus** [comment]
> Yes, the group name is set in the code, but README.md does not reflect it. Line 60 (or about) says
> 
> ```
> groupName: <YOUR_GROUP_NAME> # Use the groupName defined above
> ```
> 
> but it should match what is in the code and look like this:
> 
> ```
> groupName: com.github.dopingus.cert-manager-webhook-dynu
> ```

You're right. I updated it accordingly.

**Review by anon-software — APPROVED** [review]

**Pull request merged**
